const ADD_COMMENT = 'ADD_COMMENT';
const RESET = 'RESET';
const PRINT_COMMENT = 'PRINT_COMMENT';

const NEXT_PICTURE = 'NEXT_PICTURE';

module.exports = {
  ADD_COMMENT,
  RESET,
  PRINT_COMMENT,
  NEXT_PICTURE
};
